config/routes.rb
Rails.application.routes.draw do
  root to: "controller#action"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = Review.where(restaurant_id: params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <i class="fab fa-yelp" alt=""></i>
    <% end %>
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Restaurant List", restaurants_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Add a Restaurant", new_restaurant_path, class: "navbar-wagon-item navbar-wagon-link" %>

    </div>
  </div>
  <div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

app/views/restaurants/_form.html.erb
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%=image_url('restaurant_banner.jpg')%>);">
  <div class="banner-content">
    <h1>Welcome to Yelp Restaurants!</h1>
  </div>
</div>
<ul>
  <% @restaurants.each do |restaurant|  %>
  <li>
    <%= link_to restaurant.name, restaurant_path(restaurant)%> -
    <%= restaurant.category.capitalize %> -
    <%= link_to edit_restaurant_path(restaurant.id) do %>
    <i class="fas fa-edit"></i>
    <% end %> -
    <%= link_to restaurant_path(restaurant.id), method: :delete, data: { confirm: "Sure?" } do  %>
    <i class="fas fa-trash-alt"></i>
    <% end %>
  </li>
  <% end %>
</ul>
<p><%= link_to "Add a restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %><%= link_to edit_restaurant_path(@restaurant) do %>
    <i class="fas fa-edit"></i>
    <% end %></h1>
<ul class="list_inline" id="display-info">
  <li><%= @restaurant.category %></li>
  <li><%= @restaurant.phone_number %></li>
  <li><%= @restaurant.address %></li>
</ul>

<h3>Reviews
  <%= link_to new_restaurant_review_path(@restaurant) do  %>
    <i class="fas fa-plus"></i>
    <% end %>
  </h3>
<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= review.content %>
      -
      <%= review.rating %>
    </li>
  <% end %>
</ul>

<p><%= link_to "Go back to the list", restaurants_path %></p>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a review</h1>
<%= render 'form' %>